# Generated by Django 4.0.4 on 2022-05-31 18:19

from django.db import migrations, models
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0003_remove_post_content_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='createPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, django.views.generic.base.View),
        ),
    ]
