# Generated by Django 4.0.4 on 2022-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0005_rename_createpost_createpostmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createPostModel',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
